#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PitStopError {
    Unauthorized,
    InvalidTokenProgram,
    InvalidMintDecimals,
    InvalidTreasuryMint,
    InvalidTreasuryOwner,
    InvalidCap,
    InvalidClaimWindow,
    LockInPast,
    ZeroOutcomes,
    TooManyOutcomes,
    UnsupportedMarketType,
    UnsupportedRulesVersion,
    InvalidMarketId,
    MarketNotSeeding,
    InvalidOutcomeId,
    MaxOutcomesReached,
    OutcomeMismatch,
    SeedingIncomplete,
    TooLateToOpen,
}
